name: Build Bambu Studio on Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3


    - name: Install dependencies
      run: |
        choco install strawberryperl
        choco install visualstudio2019community
        choco install cmake
        choco install git

    - name: Install OpenSSL
      run: |
        choco install openssl
        echo "OPENSSL_ROOT_DIR=C:/Program Files/OpenSSL-Win64" >> $GITHUB_ENV
        echo "OPENSSL_LIBRARIES=C:/Program Files/OpenSSL-Win64/lib" >> $GITHUB_ENV

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/BambuStudio_dep
        key: ${{ runner.os }}-deps-v1

    
    - name: Set up dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        mkdir BambuStudio_dep
        cd deps
        mkdir build
        cd build
        cmake ../ -G "Visual Studio 16 2019" -DDESTDIR="${{ github.workspace }}/BambuStudio_dep" -DCMAKE_BUILD_TYPE=Release
        msbuild /m ALL_BUILD.vcxproj

        
    - name: Build Bambu Studio
      run: |
        mkdir install_dir
        mkdir build
        cd build
        cmake .. -G "Visual Studio 16 2019" -DBBL_RELEASE_TO_PUBLIC=1 -DCMAKE_PREFIX_PATH="${{ github.workspace }}/BambuStudio_dep/usr/local"  -DCMAKE_INSTALL_PREFIX="../install_dir" -DCMAKE_BUILD_TYPE=Release -DWIN10SDK_PATH="C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0"
        cmake --build . --target install --config Release


    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: BambuStudio_exe
        path: ./install_dir/bambu-studio.exe    


    - name: Upload artifact2
      uses: actions/upload-artifact@v4
      with:
        name: BambuStudio_exe
        path: ./install_dir

    # - name: Upload all .exe artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: BambuStudio_exe
    #     path: ./**/*.exe

    - name: Install NSIS
      run: |
        choco install nsis

    - name: Build installer
      run: |
        makensis /DPRODUCT_VERSION=1.0.0 /DPRODUCT_NAME="Bambu Studio SDH" /DINSTALLER_FILE_NAME="BambuStudioInstaller" /DPRODUCT_PUBLISHER="INUSHA" /DPRODUCT_WEB_SITE="http://www.example.com" /DINPUT_DIRECTORY="${{ github.workspace }}/install_dir" /DOUTPUT_DIRECTORY="${{ github.workspace }}/installer" "${{ github.workspace }}/path/to/installer/script.nsi"

    - name: Upload installer
      uses: actions/upload-artifact@v2
      with:
        name: BambuStudioInstaller_exe
        path: ./installer/BambuStudioInstaller.exe