name: Build Bambu Studio on Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2


    - name: Install dependencies
      run: |
        choco install strawberryperl
        choco install visualstudio2019community
        choco install cmake
        choco install git

    - name: Install OpenSSL
      run: |
        choco install openssl
        echo "OPENSSL_ROOT_DIR=C:/Program Files/OpenSSL-Win64" >> $GITHUB_ENV
        echo "OPENSSL_LIBRARIES=C:/Program Files/OpenSSL-Win64/lib" >> $GITHUB_ENV

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    # - name: Install TBB
    #   run: |
    #     choco install oneapi-cli
    #     oneapi-cli install tbb --version 2021.2.0
    #     echo "TBB_DIR=C:/Program Files (x86)/Intel/oneAPI/tbb/2021.2.0/env/.." >> $GITHUB_ENV

    # - name: Install Boost
    #   run: |
    #     choco install boost-msvc-14.2
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: BambuStudio_dep
        key: ${{ runner.os }}-deps-${{ hashFiles('**/deps/**') }}
        restore-keys: |
          ${{ runner.os }}-deps-

    - name: Set up dependencies
      shell: bash
      run: |
        if [[ ! -d "BambuStudio_dep" ]]; then
          mkdir BambuStudio_dep
          cd deps
          mkdir build
          cd build
          cmake ../ -G "Visual Studio 16 2019" -DDESTDIR="${{ github.workspace }}/BambuStudio_dep" -DCMAKE_BUILD_TYPE=Release
          msbuild /m ALL_BUILD.vcxproj
        fi
        
    - name: Build Bambu Studio
      run: |
        mkdir install_dir
        mkdir build
        cd build
        cmake .. -G "Visual Studio 16 2019" -DBBL_RELEASE_TO_PUBLIC=1 -DCMAKE_PREFIX_PATH="${{ github.workspace }}/BambuStudio_dep/usr/local"  -DCMAKE_INSTALL_PREFIX="../install_dir" -DCMAKE_BUILD_TYPE=Release -DWIN10SDK_PATH="C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0"
        cmake --build . --target install --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: BambuStudio_exe
        path: ./build/BambuStudio.exe

    - name: Upload artifact2
      uses: actions/upload-artifact@v2
      with:
        name: BambuStudio_exe
        path: ./install_dir/BambuStudio.exe        

    - name: Upload all .exe artifacts
      uses: actions/upload-artifact@v2
      with:
        name: BambuStudio_exe
        path: ./**/*.exe