name: Build Bambu Studio on Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install Boost
      run: |
        choco install boost-msvc-14.2
    
    - name: Install TBB
      run: |
        curl -L https://api.anaconda.com/download/version/2021.2.0/tbb-2021.2.0-intel_213.tar.bz2 -o tbb.tar.bz2
        tar xjf tbb.tar.bz2
        echo "TBB_DIR=${{ github.workspace }}/tbb-2021.2.0" >> $GITHUB_ENV

    - name: Set up dependencies
      run: |
        cd deps
        mkdir build
        cd build
        cmake ../ -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release
        msbuild /m ALL_BUILD.vcxproj

    - name: Build Bambu Studio
      run: |
        mkdir install_dir
        mkdir build
        cd build
        cmake .. -G "Visual Studio 16 2019" -DBBL_RELEASE_TO_PUBLIC=1 -DCMAKE_PREFIX_PATH="${{ github.workspace }}/deps/usr/local" -DCMAKE_INSTALL_PREFIX="../install_dir" -DCMAKE_BUILD_TYPE=Release -DWIN10SDK_PATH="C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0"
        cmake --build . --target install --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: BambuStudio_exe
        path: ./build/BambuStudio.exe
